project_id = "mfsozmuhudnqrjpahxdr"
[functions.chat-neotutor]
enabled = true
verify_jwt = true
import_map = "./functions/chat-neotutor/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chat-neotutor/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chat-neotutor/*.html" ]
